# Generated by Django 3.2 on 2021-06-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('jobNo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('projectName', models.CharField(max_length=80)),
                ('projectDesc', models.TextField()),
            ],
        ),
    ]
