# Generated by Django 3.2 on 2021-06-26 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('drawingNo', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('drawingDesc', models.TextField()),
                ('Quantity', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.job')),
            ],
        ),
    ]
