# Generated by Django 3.2 on 2021-08-16 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
