# Generated by Django 3.2 on 2021-06-26 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_drawing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drawing',
        ),
    ]
