# Generated by Django 3.2 on 2021-07-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20210705_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='datePublish',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
