# Generated by Django 3.2 on 2021-07-10 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20210710_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcpainting',
            name='drawing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qcpaintingdrawing', to='mysite.drawing'),
        ),
    ]
