# Generated by Django 3.2 on 2021-07-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_alter_qcpainting_drawing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machineNum',
            field=models.IntegerField(null=True),
        ),
    ]
