# Generated by Django 3.2 on 2021-06-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_drawing'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
