# Generated by Django 3.2 on 2021-07-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_painting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='name',
            field=models.CharField(default='OPAUTOTECH', max_length=20),
        ),
    ]
