# Generated by Django 3.2 on 2021-07-19 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0005_alter_machine_machinenum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numTimes', models.IntegerField()),
                ('reviseDesc', models.TextField()),
                ('datePublish', models.DateTimeField(auto_now_add=True, null=True)),
                ('dateUpdate', models.DateTimeField(auto_now=True, null=True)),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisedrawing', to='mysite.drawing')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
