# Generated by Django 3.2 on 2021-08-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_file_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_data',
            field=models.BinaryField(null=True),
        ),
    ]
