# Generated by Django 3.2 on 2021-06-30 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_drawing_qr_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drawing',
            options={'ordering': ('date',)},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('-jobNo',)},
        ),
        migrations.RemoveField(
            model_name='drawing',
            name='qr_code',
        ),
    ]
