# Generated by Django 3.2 on 2021-08-23 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_file_file_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_data',
        ),
    ]
