# Generated by Django 3.2 on 2021-10-02 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_alter_machine_machine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='machine',
        ),
    ]
