# Generated by Django 3.2 on 2021-11-30 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_alter_assembly_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drawing',
            options={'ordering': ['datePublish']},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-datePublish']},
        ),
    ]
