# Generated by Django 3.2 on 2021-12-20 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0014_auto_20211211_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepdf', models.FileField(blank=True, null=True, upload_to='file/3D-model/3D-PDF')),
                ('fileEdrawing', models.FileField(blank=True, null=True, upload_to='file/3D-model/E-Drawing')),
                ('datePublish', models.DateTimeField(auto_now_add=True, null=True)),
                ('dateUpdate', models.DateTimeField(auto_now=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filemodel', to='mysite.job')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
