# Generated by Django 3.2 on 2021-12-11 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0014_auto_20211130_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assembly',
            options={'ordering': ['datePublish']},
        ),
        migrations.AlterModelOptions(
            name='cutting',
            options={'ordering': ['datePublish']},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['datePublish']},
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['datePublish']},
        ),
        migrations.AlterModelOptions(
            name='maker',
            options={'ordering': ['datePublish']},
        ),
        migrations.AlterModelOptions(
            name='painting',
            options={'ordering': ['datePublish']},
        ),
        migrations.AlterModelOptions(
            name='qc',
            options={'ordering': ['datePublish']},
        ),
        migrations.AlterModelOptions(
            name='qcpainting',
            options={'ordering': ['datePublish']},
        ),
        migrations.CreateModel(
            name='AssemblyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='file/assembly/')),
                ('datePublish', models.DateTimeField(auto_now_add=True, null=True)),
                ('dateUpdate', models.DateTimeField(auto_now=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fileassembly', to='mysite.job')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
